// skillImages Module

const skillsImages = {
	javascript: '../public/images/icons/javaScript.png',
	react: '../public/images/icons/react.png',
	nodejs: '../public/images/icons/node-js.png',
	html: '../public/images/icons/html.png',
	css: '../public/images/icons/css.png',
	figma: '../public/images/icons/figma.png',
	mongodb: '../public/images/icons/mongodb.png',
	python: '../public/images/icons/python.png',
	fastapi: '../public/images/icons/fastapi.png',
	django: '../public/images/icons/django.png',
	postgresql: '../public/images/icons/postgresql.png',
	redis: '../public/images/icons/redis.png',
	java: '../public/images/icons/java.png',
	spring: '../public/images/icons/spring.png',
	php: '../public/images/icons/php.png',
	laravel: '../public/images/icons/laravel.png',
	symfony: '../public/images/icons/symfony.png',
	mysql: '../public/images/icons/mysql.png',
	'c#': '../public/images/icons/c-sharp.png',
	'asp.net': '../public/images/icons/asp.png',
	ruby: '../public/images/icons/ruby.png',
	'ruby on rails': '../public/images/icons/ruby_on_rails.png',
	sinatra: '../public/images/icons/sinatra.png',
	swift: '../public/images/icons/swift.png',
	kotlin: '../public/images/icons/kotlin.png',
	git: '../public/images/icons/git.png',
	github: '../public/images/icons/github.png',
	docker: '../public/images/icons/docker.png',
	postman: '../public/images/icons/postman.png',
	swagger: '../public/images/icons/swagger.png',
};

export default skillsImages;
